# Generated by Django 4.2.5 on 2023-10-05 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 10, 5, 13, 12, 38, 784067, tzinfo=datetime.timezone.utc)),
        ),
    ]
