# Generated by Django 4.2.5 on 2023-10-05 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_managers_alter_post_publish'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 10, 5, 13, 25, 59, 507781, tzinfo=datetime.timezone.utc)),
        ),
    ]
